"""Select entities for the Blauberg S21 integration."""
from __future__ import annotations

from homeassistant.components.select import SelectEntity
from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity_platform import AddEntitiesCallback

from . import BlaubergS21Coordinator, get_data
from .entity import BlaubergS21Entity

# Index matches the raw value of holding register HR_BYPASS_ROTOR_MODE.
BYPASS_MODE_OPTIONS = ["close", "open", "auto"]


async def async_setup_entry(
    hass: HomeAssistant,
    config_entry: ConfigEntry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    """Set up the Blauberg S21 selects."""
    coordinator = get_data(hass, config_entry).coordinator

    entities: list[BlaubergS21Entity] = []
    device = coordinator.data
    # bypass_type == 0 means the unit has neither a bypass nor a rotor, so the
    # entity would only ever be unavailable. Don't create it at all.
    if device is not None and device.bypass_type:
        entities.append(BlaubergS21BypassModeSelect(coordinator))
    async_add_entities(entities)


class BlaubergS21BypassModeSelect(BlaubergS21Entity, SelectEntity):
    """Bypass / rotor mode."""

    _attr_icon = "mdi:swap-horizontal"
    _attr_translation_key = "blauberg_s21_bypass_mode"
    _attr_options = BYPASS_MODE_OPTIONS

    def __init__(self, coordinator: BlaubergS21Coordinator) -> None:
        entry = coordinator.config_entry
        base_id = entry.unique_id or entry.entry_id
        # Preserve the unique id generated by releases <= 4.6.1.
        super().__init__(
            coordinator,
            key="bypass_mode",
            unique_id=f"blauberg_s21_{base_id}_bypass_mode",
        )

    @property
    def current_option(self) -> str | None:
        device = self.device
        if device is None or device.bypass_mode is None:
            return None
        if 0 <= device.bypass_mode < len(BYPASS_MODE_OPTIONS):
            return BYPASS_MODE_OPTIONS[device.bypass_mode]
        return None

    async def async_select_option(self, option: str) -> None:
        await self._async_call(
            self.client.set_bypass_mode, BYPASS_MODE_OPTIONS.index(option)
        )
